application:
  title: "IBEW Local Union 71 Membership Application"
  note: "Note that ALL fields are required."
  personal_info:
    first_name: "David"
    mi: "B"
    last_name: "McCarty"
    address: "15585 Tison Rd"
    city: "Jacksonville"
    state: "FL"
    zip: "32218"
    race: "White (Not Hispanic Origin)"
    veteran_status: "Not a Veteran"
    sex: "Male"
    last_4_ssn: "7592"
    years_at_address: "35"
    phone_number: "904-497-5870"
    date_of_birth: "05/30/1988"
    email_address: "linelife144@gmail.com"
  position_applying_for: "Journeyman Lineman"
  employed_by_electrical_contractor: "False"
  years_in_industry: "16"
  emergency_contact_name: "Elijah Smith"
  emergency_contact_phone: "904-885-1983"
  employment_history:
    - employer: "Dummy Company 1"
      start_date: "01/01/2010"
      end_date: "12/31/2015"
    - employer: "Dummy Company 2"
      start_date: "01/01/2016"
      end_date: "12/31/2020"
    - employer: "Dummy Company 3"
      start_date: "01/01/2021"
      end_date: "12/31/2022"
    - employer: "Dummy Company 4"
      start_date: "01/01/2023"
      end_date: "Present"
  member_of_ibew: "True"
  ibew_local: "429"
  ibew_card_number: "8416674"
  completed_certified_apprenticeship: "False"
  apprenticeship_details: "Dummy Apprenticeship Program, 2010"
  experience:
    climb_wood: "true"
    climb_steel: "true"
    transformers: "true"
    ncco: "False"
    distribution: "true"
    substations: "true"
    transmission: "true"
    underground: "true"
    cable_splicing: "False"
    h1: "False"
    h2: "False"
    h3: "False"
    barehanding: "False"
    welding: "true"
    operate_equipment: "true"
    concrete_slab_installation: "False"
    matting: "true"
    fencing: "true"
    directional_boring: "true"
    teledata_fiber: "False"
    osha_10: "true"
    osha_20: "true"
    osha_30: "False"
    traffic_street_lighting: "true"
    cdl: "true"
    other: false
    supervision: "true"
  operating_equipment_type: "Crane"
  cdl_type: "A"
  willing_to_travel_within_60_miles: "true"
  willing_to_travel_60_90_miles: "true"
  willing_to_travel_out_of_state: "true"
  how_heard_about_us: "Word of Mouth"
  paperwork_upload: "dummy_file.pdf"
  dues_ticket_upload: "dummy_dues.pdf"
