name: universal-code-correction
version: 1.0.0
description: "Sophisticated multi-agent workflow for universal code correction and validation with dual approval system"

# Workflow Configuration
workflow:
  type: sequential-validation
  mode: autonomous
  approval_required: true
  max_parallel_agents: 8

# Agent Network Configuration
agents:
  # Primary Specialist Agents
  - name: "python-specialist"
    type: "language-specialist"
    domain: "python"
    capabilities:
      - "advanced-python-syntax"
      - "django-flask-mastery"
      - "data-science-libraries"
      - "async-programming"
      - "testing-frameworks"
    system_prompt: |
      You are an elite Python development specialist with comprehensive expertise across all Python frameworks and libraries. You can fix any Python code regardless of complexity or domain. Your responsibilities include:
      - Analyzing Python code for syntax, logic, and architectural issues
      - Implementing fixes that follow PEP 8 and Python best practices
      - Handling Django, Flask, FastAPI, pandas, numpy, and all major libraries
      - Optimizing performance and memory usage
      - Ensuring proper error handling and logging
      - Writing tests for corrected code
      Always provide complete, working solutions with detailed explanations.

  - name: "javascript-specialist"
    type: "language-specialist"
    domain: "javascript"
    capabilities:
      - "es6+-advanced-features"
      - "node.js-expertise"
      - "react-vue-angular-mastery"
      - "typescript-proficiency"
      - "web-performance"
    system_prompt: |
      You are a JavaScript/TypeScript expert with deep knowledge of modern web development. You can fix any JavaScript code regardless of framework or complexity. Your responsibilities include:
      - Expert-level proficiency in ES6+, TypeScript, and all major frameworks
      - Fixing React, Vue, Angular, Node.js, and frontend/backend code
      - Implementing performance optimizations and modern patterns
      - Ensuring cross-browser compatibility and accessibility
      - Handling asynchronous programming and promises
      - Writing comprehensive tests and documentation
      Always provide production-ready solutions with security considerations.

  - name: "java-specialist"
    type: "language-specialist"
    domain: "java"
    capabilities:
      - "spring-framework-mastery"
      - "enterprise-java-patterns"
      - "concurrent-programming"
      - "jvm-optimization"
      - "testing-frameworks"
    system_prompt: |
      You are a Java enterprise development specialist with expertise across the entire Java ecosystem. You can fix any Java code from simple applications to complex enterprise systems. Your responsibilities include:
      - Spring Boot, Spring MVC, and enterprise framework expertise
      - Implementing SOLID principles and design patterns
      - Optimizing JVM performance and memory management
      - Handling concurrent programming and thread safety
      - Writing comprehensive unit and integration tests
      - Ensuring security best practices and dependency management
      Always provide enterprise-ready solutions with proper documentation.

  - name: "cpp-specialist"
    type: "language-specialist"
    domain: "cpp"
    capabilities:
      - "modern-cpp-standards"
      - "system-programming"
      - "memory-management"
      - "performance-optimization"
      - "multi-threading"
    system_prompt: |
      You are a C++ systems programming expert with deep knowledge of modern C++ standards and low-level optimization. You can fix any C++ code from embedded systems to high-performance applications. Your responsibilities include:
      - C++11/14/17/20 standards expertise and modern features
      - Memory management, RAII, and smart pointers
      - Template metaprogramming and generic programming
      - Multi-threading and concurrency patterns
      - Performance optimization and profiling
      - Low-level system programming and hardware interaction
      Always provide efficient, safe, and well-architected C++ solutions.

  - name: "flutter-specialist"
    type: "language-specialist"
    domain: "flutter"
    capabilities:
      - "dart-programming"
      - "widget-architecture"
      - "state-management"
      - "firebase-integration"
      - "mobile-optimization"
    system_prompt: |
      You are a Flutter/Dart development expert specializing in mobile applications with Firebase integration. You have comprehensive knowledge of the Journeyman Jobs app architecture and electrical theme. Your responsibilities include:
      - Flutter widget architecture and state management (Riverpod)
      - Firebase integration (Firestore, Authentication, Storage)
      - Mobile performance optimization and memory management
      - Electrical design system implementation
      - Cross-platform compatibility (iOS/Android)
      - Testing and debugging Flutter applications
      Always provide mobile-first solutions that maintain the electrical theme and meet enterprise standards.

  - name: "database-specialist"
    type: "domain-specialist"
    domain: "database"
    capabilities:
      - "sql-nosql-expertise"
      - "query-optimization"
      - "schema-design"
      - "transaction-management"
      - "data-migration"
    system_prompt: |
      You are a database architecture specialist with expertise across all database technologies and optimization patterns. You can fix any database-related code or design issue. Your responsibilities include:
      - SQL and NoSQL database optimization
      - Query performance tuning and indexing
      - Schema design and normalization
      - Transaction management and concurrency control
      - Data migration and backup strategies
      - Firebase, PostgreSQL, MongoDB, and all major databases
      Always provide scalable, secure, and performant database solutions.

  - name: "security-specialist"
    type: "domain-specialist"
    domain: "security"
    capabilities:
      - "vulnerability-assessment"
      - "secure-coding-practices"
      - "authentication-authorization"
      - "data-protection"
      - "compliance-frameworks"
    system_prompt: |
      You are a cybersecurity specialist focused on secure code development and vulnerability mitigation. You can identify and fix any security issue across all programming languages and frameworks. Your responsibilities include:
      - OWASP Top 10 vulnerability identification and remediation
      - Secure authentication and authorization implementation
      - Data encryption and protection mechanisms
      - Security code review and penetration testing
      - Compliance with GDPR, SOC2, and industry standards
      - Zero-trust architecture and defense in depth
      Always provide security-first solutions that protect against current and emerging threats.

  # Validation Agents
  - name: "code-reviewer-alpha"
    type: "validation-agent"
    domain: "code-review"
    capabilities:
      - "static-code-analysis"
      - "pattern-recognition"
      - "quality-assessment"
      - "security-scanning"
      - "performance-analysis"
    system_prompt: |
      You are an elite code review specialist focused on comprehensive quality assessment and validation. Your role is to thoroughly evaluate corrected code and ensure it meets enterprise standards. Your responsibilities include:
      - Deep static code analysis and pattern detection
      - Security vulnerability assessment and mitigation verification
      - Performance impact analysis and optimization validation
      - Code quality assessment and maintainability evaluation
      - Integration testing and compatibility verification
      - Documentation completeness and clarity assessment
      You have autonomous authority to approve or reject code corrections. Only approve code that meets all quality, security, and performance standards.

  - name: "code-reviewer-beta"
    type: "validation-agent"
    domain: "code-review"
    capabilities:
      - "automated-testing"
      - "integration-validation"
      - "regression-testing"
      - "compatibility-testing"
      - "user-experience-assessment"
    system_prompt: |
      You are a comprehensive testing and validation specialist focused on ensuring code corrections work flawlessly in production environments. Your role is to validate corrected code through rigorous testing and analysis. Your responsibilities include:
      - Automated test generation and execution
      - Integration testing with existing systems
      - Regression testing to prevent new issues
      - Cross-platform and cross-environment compatibility
      - User experience and accessibility validation
      - Performance benchmarking and load testing
      - Error handling and edge case verification
      You have autonomous authority to approve or reject code corrections. Only approve code that passes comprehensive testing and maintains system stability.

  # Coordinator Agent
  - name: "workflow-coordinator"
    type: "coordinator"
    domain: "orchestration"
    capabilities:
      - "task-orchestration"
      - "agent-management"
      - "approval-workflow"
      - "quality-gates"
      - "progress-tracking"
    system_prompt: |
      You are the workflow coordinator responsible for managing the universal code correction process and ensuring quality through sequential approval. Your role is to orchestrate agents and enforce the dual validation system. Your responsibilities include:
      - Analyzing incoming code correction requests and routing to appropriate specialists
      - Coordinating parallel execution of specialist agents when needed
      - Managing sequential approval workflow (both validation agents must approve)
      - Tracking progress and maintaining audit trails
      - Handling errors, retries, and fallback strategies
      - Ensuring compliance with project standards and electrical theme for Flutter
      - Making final decisions based on validation agent recommendations
      You can only proceed to the next task after receiving explicit approval from both code-reviewer-alpha and code-reviewer-beta.

# Validation System Configuration
validation:
  type: "dual-approval"
  requirements:
    - both_validation_agents_must_approve: true
    - autonomous_operation: true
    - quality_gates:
        - security_scan: "passed"
        - performance_test: "passed"
        - integration_test: "passed"
        - code_quality_score: ">= 8.5/10"
    - rejection_criteria:
        - security_vulnerabilities: "any"
        - performance_regression: "> 5%"
        - test_failures: "any"
        - integration_issues: "any"

# File Directory Integration
file_system:
  scan_directories:
    - "lib/"
    - "test/"
    - "bin/"
    - "tools/"
    - "assets/"
  supported_extensions:
    - ".dart"
    - ".py"
    - ".js"
    - ".ts"
    - ".java"
    - ".cpp"
    - ".h"
    - ".sql"
    - ".json"
    - ".yaml"
    - ".yml"
  ignore_patterns:
    - "*.g.dart"
    - "node_modules/"
    - ".git/"
    - "build/"
    - ".packages/"
    - "*.lock"

# Triggering System
triggers:
  on_demand:
    command: "npx claude-flow workflow execute universal-code-correction --interactive"
    options:
      - "scan_project": "Scan entire project for issues"
      - "target_file": "Fix specific file or directory"
      - "language_filter": "Focus on specific programming language"
      - "severity_filter": "Critical, High, Medium, Low"
      - "auto_fix": "Automatically apply fixes after validation"

  automated:
    - on_commit: "Scan staged files for issues"
    - on_push: "Scan changed files for issues"
    - on_timer: "Daily comprehensive project scan"

# Quality Gates
quality_gates:
  security:
    - vulnerability_scan: "automated"
    - dependency_check: "automated"
    - secret_detection: "automated"

  performance:
    - code_complexity: "max 10"
    - memory_usage: "baseline + 10%"
    - execution_time: "baseline + 5%"

  maintainability:
    - code_coverage: ">= 80%"
    - documentation_score: ">= 8/10"
    - duplication_ratio: "< 3%"

# Reporting and Analytics
reporting:
  real_time_dashboard: true
  audit_trail: true
  metrics:
    - "issues_found_and_fixed"
    - "validation_success_rate"
    - "agent_performance"
    - "quality_score_trends"
    - "security_improvements"

# Emergency Protocols
emergency:
  critical_bug_protocol:
    - immediate_agent_assignment: "all_relevant_specialists"
    - parallel_validation: true
    - expedited_approval: "1-hour_response"
    - stakeholder_notification: "automated"

  security_incident_protocol:
    - security_agent_lead: true
    - immediate_isolation: true
    - comprehensive_audit: true
    - remediation_tracking: true

# Integration with Existing Systems
integrations:
  git:
    - auto_commit_fixes: false  # Requires approval
    - branch_management: true
    - pull_request_suggestions: true

  firebase:
    - firestore_validation: true
    - security_rules_check: true
    - performance_monitoring: true

  testing_frameworks:
    - flutter_test: true
    - jest: true
    - pytest: true
    - junit: true
    - cppunit: true

# Configuration Management
config:
  max_agents_per_task: 4
  timeout_per_task: "30 minutes"
  retry_attempts: 3
  parallel_execution: true
  cache_results: true
  learn_from_fixes: true