openapi: 3.0.0
info:
  title: Crew Management API
  version: 1.0.0
  description: Firebase Cloud Functions API for crew operations

paths:
  /crews:
    post:
      summary: Create a new crew
      operationId: createCrew
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - preferences
              properties:
                name:
                  type: string
                  minLength: 3
                  maxLength: 50
                logoUrl:
                  type: string
                  format: uri
                preferences:
                  $ref: '#/components/schemas/CrewPreferences'
      responses:
        '201':
          description: Crew created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Crew'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /crews/{crewId}:
    get:
      summary: Get crew details
      operationId: getCrew
      parameters:
        - name: crewId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Crew details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Crew'
        '404':
          description: Crew not found
        '403':
          description: Not a member of this crew

    patch:
      summary: Update crew settings
      operationId: updateCrew
      parameters:
        - name: crewId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                logoUrl:
                  type: string
                preferences:
                  $ref: '#/components/schemas/CrewPreferences'
      responses:
        '200':
          description: Crew updated
        '403':
          description: Insufficient permissions

    delete:
      summary: Delete crew (Foreman only)
      operationId: deleteCrew
      parameters:
        - name: crewId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Crew deleted
        '403':
          description: Not the foreman

  /crews/{crewId}/members:
    get:
      summary: Get crew members
      operationId: getCrewMembers
      parameters:
        - name: crewId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of crew members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CrewMember'

    post:
      summary: Invite member to crew
      operationId: inviteMember
      parameters:
        - name: crewId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - inviteMethod
                - inviteValue
              properties:
                inviteMethod:
                  type: string
                  enum: [email, phone, userId]
                inviteValue:
                  type: string
                role:
                  type: string
                  enum: [member, lead]
                  default: member
      responses:
        '201':
          description: Invitation sent
        '403':
          description: No permission to invite

  /crews/{crewId}/members/{userId}:
    patch:
      summary: Update member role
      operationId: updateMemberRole
      parameters:
        - name: crewId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  enum: [member, lead, foreman]
      responses:
        '200':
          description: Role updated
        '403':
          description: Insufficient permissions

    delete:
      summary: Remove member from crew
      operationId: removeMember
      parameters:
        - name: crewId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Member removed
        '403':
          description: Cannot remove foreman or insufficient permissions

  /crews/{crewId}/leave:
    post:
      summary: Leave crew
      operationId: leaveCrew
      parameters:
        - name: crewId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Left crew successfully
        '400':
          description: Foreman must transfer role first

components:
  schemas:
    Crew:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        logoUrl:
          type: string
        foremanId:
          type: string
        memberIds:
          type: array
          items:
            type: string
        preferences:
          $ref: '#/components/schemas/CrewPreferences'
        createdAt:
          type: string
          format: date-time
        stats:
          $ref: '#/components/schemas/CrewStats'

    CrewPreferences:
      type: object
      properties:
        jobTypes:
          type: array
          items:
            type: string
        minHourlyRate:
          type: number
        maxDistanceMiles:
          type: integer
        preferredCompanies:
          type: array
          items:
            type: string
        requiredSkills:
          type: array
          items:
            type: string
        autoShareEnabled:
          type: boolean
        matchThreshold:
          type: integer
          minimum: 0
          maximum: 100

    CrewMember:
      type: object
      properties:
        userId:
          type: string
        crewId:
          type: string
        role:
          type: string
          enum: [foreman, lead, member]
        joinedAt:
          type: string
          format: date-time
        isAvailable:
          type: boolean

    CrewStats:
      type: object
      properties:
        totalJobsShared:
          type: integer
        totalApplications:
          type: integer
        applicationRate:
          type: number
        averageMatchScore:
          type: number
        successfulPlacements:
          type: integer